# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ea2f76a6004f1960e521f6a9db13b069e7ad0c8cf25883f96425c1b149e03407373bf1bf56728b6c7cd211a958fde0e408a481d02158c16322fd8b9ef554f1b

test:
  secret_key_base: e4eed5a1bf8859d8796e8d85b31645f65d8b7853b571415d895384a193455c702ed416bec9251e587d73e20bcbec82dfe9529bd4ddaa22d07cf60ab03c7d5bbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
